[package]
name = "rusdoo-rating"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
chrono.workspace = true
serde_json.workspace = true
uuid.workspace = true
rusdoo-core = { path = "../rusdoo-core" }
rusdoo-orm = { path = "../rusdoo-orm" }

[dev-dependencies]
rusdoo-base = { path = "../rusdoo-base" }
rusdoo-mail = { path = "../rusdoo-mail" }
rusdoo-testing = { path = "../rusdoo-testing" }
sqlx.workspace = true
tokio.workspace = true
