[package]
name = "rusdoo-project"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
serde_json.workspace = true
chrono.workspace = true
rusdoo-core = { path = "../rusdoo-core" }
rusdoo-orm = { path = "../rusdoo-orm" }
sqlx.workspace = true

[dev-dependencies]
tokio.workspace = true
sqlx.workspace = true
rusdoo-base = { path = "../rusdoo-base" }
rusdoo-testing = { path = "../rusdoo-testing" }
