[package]
name = "rusdoo-http"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
serde.workspace = true
serde_json.workspace = true
thiserror.workspace = true
tracing.workspace = true
axum.workspace = true
tokio.workspace = true
rusdoo-core = { path = "../rusdoo-core" }
rusdoo-orm = { path = "../rusdoo-orm" }
rusdoo-qweb = { path = "../rusdoo-qweb" }
quick-xml.workspace = true
rusdoo-modules = { path = "../rusdoo-modules" }
sqlx.workspace = true
argon2.workspace = true
uuid.workspace = true

[dev-dependencies]
rusdoo-testing = { path = "../rusdoo-testing" }
chrono.workspace = true
rusdoo-base = { path = "../rusdoo-base" }
rusdoo-mail = { path = "../rusdoo-mail" }
rusdoo-account = { path = "../rusdoo-account" }
rusdoo-product = { path = "../rusdoo-product" }
rusdoo-purchase = { path = "../rusdoo-purchase" }
rusdoo-sale = { path = "../rusdoo-sale" }
rusdoo-stock = { path = "../rusdoo-stock" }
tokio.workspace = true
tower.workspace = true
http-body-util = { workspace = true }
