[package]
name = "rusdoo-http"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
serde.workspace = true
serde_json.workspace = true
thiserror.workspace = true
tracing.workspace = true
axum.workspace = true
tokio.workspace = true
rusdoo-core = { path = "../rusdoo-core" }
rusdoo-orm = { path = "../rusdoo-orm" }
sqlx.workspace = true
argon2.workspace = true
uuid.workspace = true

[dev-dependencies]
tokio.workspace = true
tower.workspace = true
http-body-util = { workspace = true }
