[package]
name = "rusdoo-testing"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
serde_json.workspace = true
sqlx.workspace = true
tracing.workspace = true
rusdoo-core = { path = "../rusdoo-core" }
rusdoo-orm = { path = "../rusdoo-orm" }
rusdoo-base = { path = "../rusdoo-base" }
rusdoo-mail = { path = "../rusdoo-mail" }
rusdoo-base-vat = { path = "../rusdoo-base-vat" }
rusdoo-calendar = { path = "../rusdoo-calendar" }
rusdoo-fleet = { path = "../rusdoo-fleet" }
rusdoo-crm = { path = "../rusdoo-crm" }
rusdoo-sale-crm = { path = "../rusdoo-sale-crm" }
rusdoo-utm = { path = "../rusdoo-utm" }
rusdoo-sales-team = { path = "../rusdoo-sales-team" }
rusdoo-hr = { path = "../rusdoo-hr" }
rusdoo-hr-attendance = { path = "../rusdoo-hr-attendance" }
rusdoo-maintenance = { path = "../rusdoo-maintenance" }
rusdoo-project = { path = "../rusdoo-project" }
rusdoo-lunch = { path = "../rusdoo-lunch" }
rusdoo-phone-validation = { path = "../rusdoo-phone-validation" }
rusdoo-sale-purchase = { path = "../rusdoo-sale-purchase" }
rusdoo-resource = { path = "../rusdoo-resource" }
rusdoo-stock-account = { path = "../rusdoo-stock-account" }
rusdoo-account-check-printing = { path = "../rusdoo-account-check-printing" }
rusdoo-purchase-requisition = { path = "../rusdoo-purchase-requisition" }
rusdoo-stock-picking-batch = { path = "../rusdoo-stock-picking-batch" }
rusdoo-uom = { path = "../rusdoo-uom" }
rusdoo-product = { path = "../rusdoo-product" }
rusdoo-account = { path = "../rusdoo-account" }
rusdoo-stock = { path = "../rusdoo-stock" }
rusdoo-purchase = { path = "../rusdoo-purchase" }
rusdoo-sale = { path = "../rusdoo-sale" }

[dev-dependencies]
tokio.workspace = true
