[package]
name = "rodoo-modules"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
serde.workspace = true
serde_json.workspace = true
thiserror.workspace = true
tracing.workspace = true
rodoo-core = { path = "../rodoo-core" }
rodoo-orm = { path = "../rodoo-orm" }
