[package]
name = "rusdoo-sale-crm"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
serde_json.workspace = true
rusdoo-core = { path = "../rusdoo-core" }
rusdoo-orm = { path = "../rusdoo-orm" }

[dev-dependencies]
tokio.workspace = true
sqlx.workspace = true
rusdoo-base = { path = "../rusdoo-base" }
rusdoo-utm = { path = "../rusdoo-utm" }
rusdoo-sales-team = { path = "../rusdoo-sales-team" }
rusdoo-crm = { path = "../rusdoo-crm" }
rusdoo-product = { path = "../rusdoo-product" }
rusdoo-account = { path = "../rusdoo-account" }
rusdoo-stock = { path = "../rusdoo-stock" }
rusdoo-sale = { path = "../rusdoo-sale" }
rusdoo-testing = { path = "../rusdoo-testing" }
