{
    'name': 'Campanhas (UTM)',
    'version': '19.0.1.0',
    'category': 'Marketing',
    'summary': 'Campanhas, meios e origens: de onde veio quem chegou',
    'depends': ['base', 'web'],
    'data': [
        'security/ir.model.access.csv',
        'views/utm_campaign_views.xml',
        'views/utm_medium_views.xml',
        'views/utm_source_views.xml',
        'views/utm_stage_views.xml',
        'views/utm_tag_views.xml',
        'views/menus.xml',
        'data/utm_stage_data.xml',
        'data/utm_medium_data.xml',
        'data/utm_source_data.xml',
        'data/utm_tag_data.xml',
    ],
    'installable': True,
}
